# Generated by Django 4.2.4 on 2023-10-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNO', models.IntegerField(max_length=10)),
                ('ROLLNO', models.CharField(max_length=10)),
                ('NAME', models.CharField(max_length=255)),
                ('COMPANY', models.CharField(max_length=255)),
                ('TECHNOLOGY1', models.CharField(max_length=255)),
                ('TECHNOLOGY2', models.CharField(max_length=255)),
                ('TECHNOLOGY3', models.CharField(max_length=255)),
                ('SALARY', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DATE', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
